Add GHP_RATE_LIMIT_THRESHOLD
Since Jenkins does not retry on rate limit exceeded, we set a threshold
where GHP stops hammering GitHub to let remaining hit to Jenkins. This
fixes build failing with :

    Setting commit status on GitHub for https://github.com/owner/repo/commit/sha1
    ERROR: Step ‘Set build status on GitHub commit’ aborted due to exception:
    java.io.IOException: API rate limit reached
            at org.kohsuke.github.RateLimitHandler$2.onError(RateLimitHandler.java:58)
            at org.kohsuke.github.Requester.handleApiError(Requester.java:518)